/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Nathaniel_healthcare_beta_AbstractionLib */

#ifndef _Included_com_Nathaniel_healthcare_beta_AbstractionLib
#define _Included_com_Nathaniel_healthcare_beta_AbstractionLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Nathaniel_healthcare_beta_AbstractionLib
 * Method:    Test
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_Nathaniel_healthcare_beta_AbstractionLib_Test
  (JNIEnv *, jclass);

/*
 * Class:     com_Nathaniel_healthcare_beta_AbstractionLib
 * Method:    TMconnectDevice
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_Nathaniel_healthcare_beta_AbstractionLib_TMconnectDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_Nathaniel_healthcare_beta_AbstractionLib
 * Method:    TFmakeDevthread
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_Nathaniel_healthcare_beta_AbstractionLib_TFmakeDevthread
  (JNIEnv *, jclass);

/*
 * Class:     com_Nathaniel_healthcare_beta_AbstractionLib
 * Method:    TSpressData
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_Nathaniel_healthcare_beta_AbstractionLib_TSpressData
  (JNIEnv *, jclass);

JNIEXPORT jintArray JNICALL Java_com_Nathaniel_healthcare_beta_AbstractionLib_getData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
